    C4Context
      title System Context diagram for Internet Banking System
      Enterprise_Boundary(b0, "Order CRUD") {
        Person(customerA, "Cliente", "Cliente que deseja fazer um pedido")
        Person(customerB, "Vendedor")
        System(SystemOrder, "Order CRUD System", "Sistema da aplicação")


        Enterprise_Boundary(b1, "Container") {
          SystemDb_Ext(SystemAPI, "API", "Executa as funcionalidades do sistema através de requisições via JSON/HTTP")

          Boundary(b2, "Componentes") {
            SystemDb_Ext(SystemGet, "Get Controller", "Lista informações")
            SystemDb_Ext(SystemPost, "Post Controller", "Cria informações")
            SystemDb_Ext(SystemPut, "Put Controller", "Atualiza informações")
            SystemDb_Ext(SystemDelete, "Delete Controller", "Deleta informações")
          }
            Boundary(b3, "Database") {
              SystemDb_Ext(SystemBD, "DataBase", "Armazena os dados do sistema")
            }
        }
      }

      BiRel(customerA, customerB, "Pede")
      BiRel(customerB, SystemOrder, "Abre chamado")
      BiRel(SystemOrder, SystemAPI, "Faz requisição")
      BiRel(SystemAPI, SystemGet, "Verifica os dados necessários")
      BiRel(SystemAPI, SystemPost, "Verifica os dados necessários")
      BiRel(SystemAPI, SystemPut, "Verifica os dados necessários")
      BiRel(SystemAPI, SystemDelete, "Verifica os dados necessários")
      BiRel(SystemGet, SystemBD, "Verifica os dados necessários")
      BiRel(SystemPost, SystemBD, "Verifica os dados necessários")
      BiRel(SystemPut, SystemBD, "Verifica os dados necessários")
      BiRel(SystemDelete, SystemBD, "Verifica os dados necessários")
      BiRel(SystemBD, SystemAPI, "Retorna a verificação")
      BiRel(SystemAPI, SystemOrder, "Retorna o resultado da requisição")
      BiRel(SystemOrder, customerA, "Retorna o resultado para o cliente")