---
title: Entity Relationship Diagram Order CRUD
---
erDiagram
    Cliente{
        Serial id_cliente PK
        Varchar(60) nome_cliente
        Varchar telefone_cliente
        Float saldo
    }

    Vendedor{
        Serial id_vendedor PK
        Varchar(60) nome_vendedor
    }

    Pedido{
        Serial id_pedido PK
        timestamptz data_pedido
        Varchar status_pedido
        Float valor_pedido
        Integer id_cliente FK
        Integer id_vendedor FK 
    }

    Produto{
        Serial produto_id PK
        Varchar(60) nome_produto
        Float valor_produto
        Integer estoque
    }

    ProdutoPedido{
        Integer id_pedido FK
        Integer produto_id FK
        Integer quantidade
    }

    Cliente ||--o{ Pedido : Faz
    Vendedor ||--|{ Pedido : Vende
    Pedido ||--|{ ProdutoPedido : AdicionaProduto
    Produto ||--o{ ProdutoPedido : AdicionadoAoPedido