---
title: Sequence Diagram Order CRUD
---

sequenceDiagram
    participant Client
    participant Controllers
    participant Validators
    participant Adapters
    participant BD


    Client->>Controllers: Cadastrar produtos
    Controllers->>Adapters: Ler a requisição
    alt  Requisição inválida
        Adapters->>Controllers: Erro
        Controllers->>Client: Erro
    else Requisição válida
        Adapters->>Controllers: nil
    end
    Controllers->>Validators: Validar dados passados pelo Client
    alt  Dados válidos
        Validators->>Controllers: Nil
    else Dados inválidos
        Validators->>Controllers: Erro
        Controllers->>Client: Erro
    end
    Controllers->>Adapters: Verifica se o produto existe
    alt  Produto não existe
        Adapters->>Controllers: Nil
    else Produto já existe
        Validators->>Controllers: Erro
        Controllers->>Client: Erro
    end
    
