---
title: Sequence Diagram Order CRUD
---

sequenceDiagram
    participant Client
    participant Controllers
    participant Validators
    participant Adapters
    participant BD


    Client->>Controllers: Cadastrar produtos
    Controllers->>Controllers: Ler a requisição
    alt  Requisição inválida
        Controllers->>Controllers: Erro
        Controllers->>Client: Erro
    else Requisição válida
        Controllers->>Controllers: nil
    end
    Controllers->>Validators: Validar dados passados pelo Client
    alt  Dados válidos
        Validators->>Controllers: Nil
    else Dados inválidos
        Validators->>Controllers: Erro
        Controllers->>Client: Erro
    end
    Controllers->>Adapters: Verificar se o produto existe
    Adapters->>BD: Consulta no banco
    BD->>Adapters: Retorna resultado
    alt  Produto não existe
        Adapters->>Controllers: Nil
    else Produto já existe
        Validators->>Controllers: Erro
        Controllers->>Client: Erro
    end
    Controllers->>Adapters: Criar produto
    Adapters->>BD: Criar produto
    alt  Criação feita
        BD->>Adapters: Nil
    else Erro na criação
        BD->>Adapters: Erro
        Adapters->>Controllers: Erro
        Controllers->>Client: Erro
    end
    Adapters->>Controllers: Mensagem de sucesso
    Controllers->>Client: Mensagem de sucesso
    
